# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Basic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: check-added-large-files

  # Terraform hooks
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.18
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint

  # Run terragrunt hclfmt
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.18
    hooks:
      - id: terragrunt-hclfmt

  # Trufflehog (secret scanning)
  - repo: https://github.com/trufflesecurity/trufflehog.git
    rev: v3.28.6
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: trufflehog git file://. --since-commit HEAD --fail
        language: golang
        fail_fast: true
        pass_filenames: false

  # Run terraform-docs
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.52.0
    hooks:
      - id: terraform_docs

  # Run tfsec (leaving this commented until a healthy baseline is established, as per PLT-473)
  - repo: https://github.com/tfsec/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec
