name: Leaked Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #https://github.com/marketplace/actions/trufflehog-oss
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.80.5
        with:
          path: ./
          base: ""
          head: ${{ github.ref_name}}
          extra_args: --debug --only-verified
